# -*- coding: utf-8 -*-
"""breast_cancer

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/17mgbL36YRZPJms0OyENBqTQFPsNiVF6n

# Logistic Regression

## Importing the libraries
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

"""## Importing the dataset"""

data = pd.read_csv('breast_cancer.csv')
X = data.iloc[:, 1:-1].values
y = data.iloc[:, -1].values

"""## Splitting the dataset into the Training set and Test set"""

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2 , random_state=0)
# random_state = 0 because it will allow us to set a seed in order to have same result of randomness because the
# split is going to be done randomly.

"""## Training the Logistic Regression model on the Training set"""

from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression(random_state=0)
classifier.fit(X_train, y_train)

"""## Predicting the Test set results"""

y_pred = classifier.predict(X_test)

"""## Making the Confusion Matrix"""

from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)
# 84 are right predictions that the tumor is benign
# 47 are right predictions that tumor is maligant
# 3 are wrong predictions that the tumor is benign
# 3 are wrong predictions that the tumore is malignat
# 84+47 are right predictions and 3 incorrect predictions.

(84+47)/(84+47+3+3)

"""## Computing the accuracy with k-Fold Cross Validation"""

from sklearn.model_selection import cross_val_score      # cross_val_score function helps to get the sccracy of 10 train test falls
accuracies = cross_val_score(estimator = classifier, X = X_train, y = y_train, cv = 10)
print("Accuracy : {:.2f} %".format(accuracies.mean()*100))    # .format is way of writing in python
print("Standard Deviation : {:.2f} %".format(accuracies.std()*100))

# std is pretty low and that is good. i.e accracy lies between 94.73% and 98.7%

